version: '3.8'

services:

  # Django
  web:
    build: .
    command: gunicorn Django_HW.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis


  # Nginx
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web


  # Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"


  # Celery worker
  celery-worker:
    build: .
    command: celery --app Django_HW worker
    volumes:
      - .:/app
    depends_on:
      - db
      - web
      - redis


  # Celery Beat
  celery-beat:
    build: .
    command: celery --app Django_HW beat
    volumes:
      - .:/app
    depends_on:
      - db
      - web
      - redis


  # Postgres
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"


volumes:
  postgres_data: